variables:
  KUBECTL_CONFIG: $KUBECTL_CONFIG
  IMAGEM_DOCKER: registry.fslab.dev/pablosmolak/api-academia
  DATABASE_URL: "mysql://root:test1234@mysql-academia:3306/academiaFSlab"

stages:
  - build
  - deploy

buildar-docker:
  stage: build
  image: docker:dind
  only:
    - 19-implementar-funcoes-de-conteudo
  script:
    - cp .env.example .env 
    - >
      docker build 
      -t $IMAGEM_DOCKER
      -f DockerFile
      .
    - docker push $IMAGEM_DOCKER

fazer-deploy:
  stage: deploy
  needs: ['buildar-docker']
  image:
    name: bitnami/kubectl:latest
    entrypoint: ['']
  only:
    - 19-implementar-funcoes-de-conteudo
  script:
    - cat $KUBECTL_CONFIG > ~/.kube/config
    - kubectl config get-contexts
    - kubectl get node
    - kubectl get pods
    - kubectl delete deployment api-academia || true
    - kubectl apply -f deployment.yaml
    - sleep 60
    - kubectl get pods
    - kubectl describe deploy/api-academia
    - kubectl logs deploy/api-academia
