FROM node:20-alpine3.21

# Instala o OpenSSL 1.1 necessário para o Prisma
RUN apk add --no-cache bash openssl

# Define o diretório de trabalho
WORKDIR /node-app

# Define as variáveis de ambiente
ENV PORT=3000
EXPOSE 3000

# Copia e instala as dependências
COPY package.json package-lock.json ./
RUN npm ci

# Copia o restante do código para dentro do container
COPY . .

# Gera os artefatos do Prisma
RUN npx prisma generate

# Ponto de partida da aplicação
CMD ["node", "server.js"]
