version: '3.8'

services:
  minio:
    image: quay.io/minio/minio
    container_name: minio1
    ports:
      - "9000:9000"  # Porta do serviço MinIO
      - "9001:9001"  # Porta da console administrativa
    environment:
      MINIO_ROOT_USER: ROOTUSER      # Usuário admin
      MINIO_ROOT_PASSWORD: CHANGEME123 # Senha admin
    volumes:
      - ./data_minio:/data                 # Volume para os dados do MinIO
    command: server /data --console-address ":9001"  # Comando para iniciar o MinIO
