apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rubix-mysql
spec:
  resources:
    requests:
      storage: 2Gi
  accessModes:
    - ReadWriteOnce
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rubix-mysql
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: rubix-mysql
  template:
    metadata:
      labels:
        app: rubix-mysql
    spec:
      containers:
      - name: mysql
        image: mysql:8
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "pablo123"
        - name: MYSQL_DATABASE
          value: "academiaFSlab"
        - name: MYSQL_USER
          value: "pablo"
        - name: MYSQL_PASSWORD
          value: "pablo123"
        ports:
        - containerPort: 3306
        volumeMounts:
          - mountPath: /var/lib/mysql
            name: pv
      volumes:
      - name: pv
        persistentVolumeClaim:
          claimName: rubix-mysql
---
apiVersion: v1
kind: Service
metadata:
  name: rubix-mysql
spec:
  type: ClusterIP
  selector:
    app: rubix-mysql
  ports:
  - port: 3306
    targetPort: 3306
