apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rubix-minio
spec:
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rubix-minio
spec:
  selector:
    matchLabels:
      app: rubix-minio
  template:
    metadata:
      labels:
        app: rubix-minio
    spec:
      containers:
      - name: rubix-minio
        image: quay.io/minio/minio:latest
        args: ["server","/data","--console-address",":9001"]
        resources: {}
        ports:
        - containerPort: 9000
        - containerPort: 9001
        envFrom:
        - configMapRef:
            name: rubix-minio-config
        - secretRef:
            name: rubix-minio-secret
        volumeMounts:
          - mountPath: /data
            name: pv
      volumes:
      - name: pv
        persistentVolumeClaim:
          claimName: rubix-minio
---
apiVersion: v1
kind: Service
metadata:
# Nome de host do minio
  name: rubix-minio-server
spec:
  type: ClusterIP
  selector:
    app: rubix-minio
  ports:
  - port: 9000
    targetPort: 9000
---
apiVersion: v1
kind: Service
metadata:
# Nome de host do minio console
  name: rubix-minio
spec:
  type: ClusterIP
  selector:
    app: rubix-minio
  ports:
  - port: 80
    targetPort: 9001
